version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    volumes:
      - mongodb_vol:/data/db

  dash_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dash_app_container
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=books_db
      - NAME=SomeName
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_vol: ./backend/data/db