version: '3'
services:
  mongodb:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mongodb_container
    ports:
      - '27017:27017'
    volumes:
      - ./backend/data/db:/data/db

  dash_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dash_app_container
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - USERNAME=jonas
      - PASSWORD=admin2023
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
